### ISSUE TITLE
How could we rebuild our own kinase structures by taking advantage of KinFragLib codes?

### ISSUE THREAD

**Issue by chf42** [volkamerlab/KinFragLib#47]
Hi All,

Thank you for developing KinFragLib! That is exactly a great approach for knowledge-based kinase inhibitor design. 

I wonder how I could use KinFragLib fragmentation & recombination codes for my own kinase inhibitor design. For example, I have a kinase inhibitor that I only wanted to replace the AP region with all AP fragments stored in KinFragLib. Is it possible for me to do that? 

In another case, if I would like to do fragmentation & recombination from other kinase inhibitor collections, how could I do that?

Thanks!
Cheng

**Comment by AndreaVolkamer** [comment]
Dear @chf42,

thanks for your interest in our work and your warm words about KinFragLib!

Regarding your questions:
-    own inhibitor design: We are currently working on an extension that allows to filter the fragments in KinFragLib according to user defined constrains, which will include user defined fragments. but it is not yet included. I will keep you updated on this.
-    own kinase inhibitor collection fragmentation&recombination: This application is not easily doable with the current implementation. We heavily rely on the KLIFS database, and the respective available PDB structures, to allow for the subpocket enhanced fragmentation.

Best, Andrea

**Comment by chf42** [comment]
> 

Dear Andrea,

Thank you for your quick response! Looking forward to the new updates. I will also read your paper in more details.

In my mind, it would be great to have a "recombination" function that takes the lead inhibitor structure, the region that the users want to replace, and the fragments stored in your database as the parameters. That's probably something already in your development plan, I guess. 

Thank you!
Cheng

**Comment by dominiquesydow** [comment]
Hi @chf42,

Extending on what Andrea was mentioning already, in case you are using KLIFS structures, you could do your own fragmentation and recombination using this code base (README contains usage instructions):
https://github.com/volkamerlab/KinaseFocusedFragmentLibrary

> In my mind, it would be great to have a "recombination" function that takes the lead inhibitor structure, the region that the users want to replace, and the fragments stored in your database as the parameters. That's probably something already in your development plan, I guess.

Totally agreed, this is indeed something we still have on our TODO list. If you wanted to try this out already, you could use the aforementioned recombination code. The [subpocket fragment SDF files](https://github.com/volkamerlab/KinFragLib/tree/master/data/fragment_library) would need the following updates:
- Select your "lead inhibitor structure" - would mean to keep only the structure(s) of interest in the SDF file of your starting point subpocket
- Keep only SDF files for the subpockets that you are interested in expanding into (this will need a code update because empty SDF files are not accounted for at the moment, see https://github.com/volkamerlab/KinaseFocusedFragmentLibrary/issues/26)

Once we have an update on this, we'll let you know here!

**Comment by dominiquesydow** [comment]
@chf42 this should work now on the `master` branch. Please re-open this issue if you run into troubles, thank you!
